{% from "dockers/dockerfile-macros.j2" import install_debian_packages %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Pre-install the fundamental packages
RUN apt-get update \
 && apt-get -y install  \
    gdb                 \
    libboost-atomic1.74.0

COPY \
{% for deb in docker_saiserver_xsight_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_saiserver_xsight_debs.split(' ')) }}

RUN apt-get install -y libjudy-dev libqt5core5a libqt5network5 libpcap0.8 libasan5 pciutils

COPY ["start.sh", "/usr/bin/"]
COPY ["profile.ini", "portmap.ini", "/etc/sai/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]
