# name          lanes             alias             index       speed
Ethernet1       1                 Ethernet1         0           100000
Ethernet2       2                 Ethernet2         1           100000
Ethernet3       3                 Ethernet3         2           100000
Ethernet4       4                 Ethernet4         3           100000
