#!/usr/bin/python3

try:
    from sonic_py_common import logger
    from sonic_platform import bmc
except ImportError as e:
    raise ImportError(str(e) + "- required module not found")

def cold_reset():
    bmccmd = bmc.Bmc()
    bmccmd.cold_reset()

def main():
    cold_reset()

if __name__ == "__main__":
    main()

