{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

## Pre-install the fundamental packages
RUN apt-get update \
 && apt-get -y install  \
    net-tools           \
    python3-pip         \
    python3-dev         \
    python-is-python3   \
    python3-scapy       \
    build-essential     \
    libssl-dev          \
    libffi-dev          \
    wget                \
    cmake               \
    libnanomsg5         \
    libnanomsg-dev      \
    libthrift-0.17.0

COPY \
{% for deb in docker_syncd_xsight_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN apt-get install -y libjudy-dev libpcap0.8 libjsoncpp25 libasan6 pciutils

{{ install_debian_packages(docker_syncd_xsight_debs.split(' ')) }}

COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor/"]
RUN ln -s /usr/lib/x86_64-linux-gnu/libjsoncpp.so.25 /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1

## Clean up
RUN apt-get -y purge \
    cmake            \
    libssl-dev       \
    libffi-dev       \
    python3-dev      \
    python3-pip      \
    libthrift-dev    \
    build-essential

RUN apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]
