# name          lanes   alias         index       speed
Ethernet0       0       QSFP-DD1      0           100000
Ethernet1       1       QSFP-DD2      1           100000
Ethernet2       2       QSFP-DD3      2           100000
Ethernet3       3       QSFP-DD4      3           100000
Ethernet4       4       QSFP-DD5      4           100000
Ethernet5       5       QSFP-DD6      5           100000
Ethernet6       6       QSFP-DD7      6           100000
Ethernet7       7       QSFP-DD8      7           100000
Ethernet8       8       QSFP-DD9      8           100000
Ethernet9       9       QSFP-DD10     9           100000
Ethernet10      10      QSFP-DD11     10          100000
Ethernet11      11      QSFP-DD12     11          100000
Ethernet12      12      QSFP-DD13     12          100000
Ethernet13      13      QSFP-DD14     13          100000
Ethernet14      14      QSFP-DD15     14          100000
Ethernet15      15      QSFP-DD16     15          100000
