# Xsight Platform modules
XSIGHT_X2EVB_PLATFORM_MODULE_VERSION = 1.1

export XSIGHT_X2EVB_PLATFORM_MODULE_VERSION

XSIGHT_X2EVB_PLATFORM_MODULE = sonic-platform-xsight-x2evb_$(XSIGHT_X2EVB_PLATFORM_MODULE_VERSION)_amd64.deb
$(XSIGHT_X2EVB_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-xsight
$(XSIGHT_X2EVB_PLATFORM_MODULE)_PLATFORM = x86_64-x2evb-r0
$(XSIGHT_X2EVB_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(XSIGHT_X2EVB_PLATFORM_MODULE)

$(eval $(call add_extra_package,$(XSIGHT_X2EVB_PLATFORM_MODULE)))
