# XSight SAI

XSIGHT_URL = file:///sonic

XSIGHT_LIBSAI = xsai-main_0.1_all.deb
XSIGHT_LIBSAI_DEV = xsai-main-dev_0.1_all.deb

$(XSIGHT_LIBSAI)_URL = $(XSIGHT_URL)/$(XSIGHT_LIBSAI)
$(XSIGHT_LIBSAI_DEV)_URL = $(XSIGHT_URL)/$(XSIGHT_LIBSAI_DEV)
$(XSIGHT_LIBSAI)_DEPENDS += $(LIBTHRIFT_DEV)
$(XSIGHT_LIBSAI)_RDEPENDS += $(LIBTHRIFT_DEV)

$(eval $(call add_derived_package,$(XSIGHT_LIBSAI),$(XSIGHT_LIBSAI_DEV)))

SONIC_ONLINE_DEBS += $(XSIGHT_LIBSAI)

$(XSIGHT_LIBSAI_DEV)_DEPENDS += $(XSIGHT_LIBSAI)
$(eval $(call add_conflict_package,$(XSIGHT_LIBSAI_DEV),$(LIBSAIVS_DEV)))
