# XSight SAI

XSIGHT_LIBSAI_VERSION = 0.1
XSIGHT_LIBSAI_URL_PREFIX = "file:///sonic"

XSIGHT_LIBSAI = xsai-main_$(XSIGHT_LIBSAI_VERSION)_all.deb
XSIGHT_LIBSAI_DEV = xsai-main-dev_$(XSIGHT_LIBSAI_VERSION)_all.deb
XSIGHT_XBM = xbm_$(XSIGHT_LIBSAI_VERSION)_all.deb

$(XSIGHT_LIBSAI)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_LIBSAI)"
$(eval $(call add_derived_package,$(XSIGHT_LIBSAI),$(XSIGHT_LIBSAI_DEV)))
$(XSIGHT_LIBSAI_DEV)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_LIBSAI_DEV)"
ifeq ($(SAITHRIFT_V2),y)
$(XSIGHT_LIBSAI)_DEPENDS += $(LIBTHRIFT_0_14_1)
$(XSIGHT_LIBSAI)_RDEPENDS += $(LIBTHRIFT_0_14_1)
else
$(XSIGHT_LIBSAI)_DEPENDS += $(LIBTHRIFT)
$(XSIGHT_LIBSAI)_RDEPENDS += $(LIBTHRIFT)
endif

XBM_EXISTS := $(or $(and $(wildcard $(XSIGHT_XBM)),y),n)

ifeq ($(XBM_EXISTS),y)
$(XSIGHT_XBM)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_XBM)"
ifeq ($(SAITHRIFT_V2),y)
$(XSIGHT_XBM)_RDEPENDS += $(LIBTHRIFT_0_14_1)
else
$(XSIGHT_XBM)_RDEPENDS += $(LIBTHRIFT)
endif
$(XSIGHT_LIBSAI)_DEPENDS += $(XSIGHT_XBM)
$(XSIGHT_LIBSAI)_RDEPENDS += $(XSIGHT_XBM)
SONIC_ONLINE_DEBS += $(XSIGHT_XBM)
endif

SONIC_ONLINE_DEBS += $(XSIGHT_LIBSAI)

$(eval $(call add_conflict_package,$(XSIGHT_LIBSAI_DEV),$(LIBSAIVS_DEV)))
