# XSight SAI

XSIGHT_LIBSAI_VERSION = 0.1
XSIGHT_LIBSAI_VERSION_GITHUB = 1.15.0-0
XSIGHT_LIBSAI_URL_PREFIX = "file:///sonic"

XSIGHT_LIBSAI = xsai-main_$(XSIGHT_LIBSAI_VERSION)_all.deb
XSIGHT_LIBSAI_DEV = xsai-main-dev_$(XSIGHT_LIBSAI_VERSION)_all.deb
XSIGHT_XBM = xbm_$(XSIGHT_LIBSAI_VERSION)_all.deb

XSIGHT_LIBSAI_GITHUB = xsai-main_$(XSIGHT_LIBSAI_VERSION_GITHUB)_amd64.deb
XSIGHT_LIBSAI_DEV_GITHUB = xsai-main-dev_$(XSIGHT_LIBSAI_VERSION_GITHUB)_amd64.deb

XBM_EXISTS := $(or $(and $(wildcard $(XSIGHT_XBM)),y),n)
LIBSAI_EXISTS := $(or $(and $(wildcard $(XSIGHT_LIBSAI)),y),n)

$(XSIGHT_LIBSAI)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_LIBSAI)"
ifeq ($(LIBSAI_EXISTS),y)
$(eval $(call add_derived_package,$(XSIGHT_LIBSAI),$(XSIGHT_LIBSAI_DEV)))
else
$(eval $(call add_derived_package,$(XSIGHT_LIBSAI_GITHUB),$(XSIGHT_LIBSAI_DEV_GITHUB)))
endif
$(XSIGHT_LIBSAI_DEV)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_LIBSAI_DEV)"
$(XSIGHT_LIBSAI)_DEPENDS += $(LIBTHRIFT_0_22_0)
$(XSIGHT_LIBSAI)_RDEPENDS += $(LIBTHRIFT_0_22_0)

$(XSIGHT_LIBSAI_GITHUB)_URL = "https://github.com/Xsight-Labs/SONiC/raw/refs/heads/main/amd64/sai-plugin/202411/$(XSIGHT_LIBSAI_GITHUB)"
$(XSIGHT_LIBSAI_DEV_GITHUB)_URL = "https://github.com/Xsight-Labs/SONiC/raw/refs/heads/main/amd64/sai-plugin/202411/$(XSIGHT_LIBSAI_DEV_GITHUB)"
$(XSIGHT_LIBSAI_GITHUB)_DEPENDS += $(LIBTHRIFT_0_22_0)
$(XSIGHT_LIBSAI_GITHUB)_RDEPENDS += $(LIBTHRIFT_0_22_0)

ifeq ($(XBM_EXISTS),y)
$(XSIGHT_XBM)_URL = "$(XSIGHT_LIBSAI_URL_PREFIX)/$(XSIGHT_XBM)"
$(XSIGHT_XBM)_RDEPENDS += $(LIBTHRIFT_0_22_0)
ifeq ($(LIBSAI_EXISTS),y)
$(XSIGHT_LIBSAI)_DEPENDS += $(XSIGHT_XBM)
$(XSIGHT_LIBSAI)_RDEPENDS += $(XSIGHT_XBM)
else
$(XSIGHT_LIBSAI_GITHUB)_DEPENDS += $(XSIGHT_XBM)
$(XSIGHT_LIBSAI_GITHUB)_RDEPENDS += $(XSIGHT_XBM)
endif
SONIC_ONLINE_DEBS += $(XSIGHT_XBM)
endif


ifeq ($(LIBSAI_EXISTS),y)
SONIC_ONLINE_DEBS += $(XSIGHT_LIBSAI)
else
SONIC_ONLINE_DEBS += $(XSIGHT_LIBSAI_GITHUB)
endif


ifeq ($(LIBSAI_EXISTS),y)
$(eval $(call add_conflict_package,$(XSIGHT_LIBSAI_DEV),$(LIBSAIVS_DEV)))
else
$(eval $(call add_conflict_package,$(XSIGHT_LIBSAI_DEV_GITHUB),$(LIBSAIVS_DEV)))
endif
