# name           lanes          alias     index    speed
Ethernet0        0              etp1      1        100000
Ethernet1        1              etp2      2        100000
Ethernet2        2              etp3      3        100000
Ethernet3        3              etp4      4        100000
Ethernet4        4              etp5      5        100000
Ethernet5        5              etp6      6        100000
Ethernet6        6              etp7      7        100000
Ethernet7        7              etp8      8        100000
Ethernet8        8              etp9      9        100000
Ethernet9        9              etp10     10       100000
Ethernet10       10             etp11     11       100000
Ethernet11       11             etp12     12       100000
Ethernet12       12             etp13     13       100000
Ethernet13       13             etp14     14       100000
Ethernet14       14             etp15     15       100000
Ethernet15       15             etp16     16       100000
